name: Onboard to Membrowse

on:
  workflow_dispatch:

jobs:
  onboard:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Renesas-RA packages
        run: source tools/ci.sh && ci_renesas_ra_setup
      
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: renesas-ra-build
      
      - name: Run Membrowse Onboard Action
        uses: membrowse/membrowse-action/onboard-action@main
        with:
          target_name: renesas-ra
          num_commits: 2
          build_script: source tools/ci.sh && ci_renesas_ra_setup && ci_renesas_ra_board_build
          elf: ports/renesas-ra/build-EK_RA6M2/firmware.elf
          ld: ports/renesas-ra/boards/EK_RA6M2/ra6m2_ek.ld
          api_key: ${{ secrets.MEMBROWSE_API_KEY }}